apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - namespace.yaml
  - keycloak.yaml
  - ingress.yaml

secretGenerator:
  - name: keycloak-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=certs/tls.crt
      - tls.key=certs/tls.key
    options:
      disableNameSuffixHash: true

configMapGenerator:
  - name: keycloak-realm-config
    files:
      - argocd-realm.json
    options:
      disableNameSuffixHash: true
