apiVersion: v1
kind: Secret
metadata:
  name: oidc-config
  labels:
    app.kubernetes.io/name: oidc-config
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  keycloakClientSecret: YUpaa2tFQXNxbDJIakY4TE13NXc5U2FwNUZEaTg4Q0E=

